### ISSUE TITLE
Footer: misprint in 'Contact Us'

### ISSUE THREAD

**Issue by ybalenko** [valentinavolgina2/sunny-hikes#35]
Steps:
1. Go to the homepage
2. Scroll down to a footer

Actual result: Cotact us
Expected result: Contact us

**Comment by ybalenko** [comment]
- [ ] Fix
- [ ] Test

**Comment by valentinavolgina2** [comment]
Fixed

**Comment by ybalenko** [comment]
https://warm-river-49749.herokuapp.com/hikes at this page is not fixed

**Comment by valentinavolgina2** [comment]
Fixed everywhere

**Comment by ybalenko** [comment]
Verified.
